In [3]:
from IPython.core.display import display_html
import pandas as pd
import math

df = pd.DataFrame()
df = pd.read_csv('/content/knn.csv')
print(df)

print("\n************************************************************************\n")
df.info()

print("\n\n**********************************************************************************************************************************\n")

distance = []

for i in range(5):
    distance.append(math.sqrt(pow(int(df.iloc[i,1])-int(df.iloc[5,1]),2) + pow(int(df.iloc[i,2])-int(df.iloc[5,2]),2) + pow(int(df.iloc[i,3])-int(df.iloc[5,3]),2) ))

print("Euclidean distances are  --> ", distance)

sort = sorted(distance)
print("\nSorted Euclidean distances are  --> ", sort)

print("\n**********************************************************************************************************************************\n")

t1 = distance.index(sort[0])
t2 = distance.index(sort[1])
t3 = distance.index(sort[2])

print(str(t1) + " " + str(t2) + " " + str(t3) )

  coustomer  age  Income   no credit cards class
0    George   35       35                3    No
1    Rachel   22       50                2   Yes
2     Steve   63      200                1    No
3       Tom   59      170                1    No
4      Anne   25       40                4   Yes
5      John   37       50                2    Na

************************************************************************

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   coustomer        6 non-null      object
 1   age              6 non-null      int64
 2   Income           6 non-null      int64
 3   no credit cards  6 non-null      int64
 4   class            6 non-null      object
dtypes: int64(3), object(2)
memory usage: 368.0+ bytes


**********************************************************************************************************************************

Euclidean distances are  -->  [15.165750888103101, 15.0, 152.23994219652081, 122.00409829181969, 15.748015748023622]

Sorted Euclidean distances are  -->  [15.0, 15.165750888103101, 15.748015748023622, 122.00409829181969, 152.23994219652081]

**********************************************************************************************************************************

1 0 4